### ISSUE TITLE
[Survival] Gamemode Concept

### ISSUE THREAD

**Issue by West107** [imperialvalordev/helpdesk#20]
### Feature

Maps:
Regular 1.19 World 15,000 by 15,000 border 
Custom realistic world map (whichever model is around the same as the 15x15 border of the 1.19 world)
Spawn is the OG Survival spawn
(People can switch between them easily with the same inventories,ect)

Economy:
People can setup shops with any item and price they want
People can sell most items and get money

Ranks:
All ranks get basic playable perks such as 
tpa
tpahere
trade
back
home
delhome
seen
ignore
sethome
mystats
warps

Ranks will be Roman Numerals [IV VII]
People rankup through playtime 
I - 1 day - 3 homes - 500$
II - 3 days - 5 homes - 1k
III - 7 days - 7 homes - 2k
IV - 14 days - 10 homes - 5k
V - 30 days - 12 homes - 10k
VI - 50 Days - 18 homes - 25k
VII - 75 Days - 20 homes - 50k
VIII - 100 Days - 22 homes - 100k
IX - 125 Days - 25 homes - 150k
X - 150 Days - 30 homes - 250k

Spawn features:
Has npc/places to sell and buy items
RTP portal (5 min cooldown)

Claims:
Use Ultimate claims (I have it)

Custom Recipes:
Blackstone (regular stone with coal)
Enchanted Golden Apple OG Recipe
Saddles and horse armor

### Ideal solution or implementation

Send me plugin or plugin ideas for best implementation of the above features 

### Other context

Plugins:
Mcmmo
hdb

### The platform for which your plugin is to be built against

Whatever is best

**Comment by aarushbhutra** [comment]
Its gonna be hard to use the old spawn as its an old version and its in a survival world which means everything else in the world will also be there

**Comment by Whitescan** [comment]
I've got some feedback about this.

**Map**
1) 15x15k is like... SMALL... We need 50x50k at least. You can run 15k blocks in 2 hourish
2) there are no good world generators available for 1.19 yet
3) Should be easy with a citizen that sends people from the spawn to a random location in survival

**Economy**
What can I say? This will be BROKEN. Our economy will be ruined exceptionally fast and there is no way for us to find out what actually happens. Decentralised shops are never a good idea. 
When looking at the real world there are big companies that set the prices to a minimum amount.
We, as the server, have to be in that position. Otherwise rich people start selling their diamonds for a dollar and new players get full diamond with their starting balance at a certain point.
I suggest going with an actionhouse and trade plugin. That way we can tax every transaction and make sure to keep voiding money when ever it's used.

**Ranks**
Those are a lot of ranks. I'm not quite sure how this will be beneficial since the perks per rank will be rather low...

**Spawn**
Unsure why this has it's own category in the concept but I already talked about this in the **Map** section.
NPCs such as guides and easy access to certain important features will be added.

**Claims**
I noticed A LOT of software on our servers that will efficiently block us from getting any support anywhere.
Because they are on the [list of shame](https://kennytv.github.io/list-of-shame/) from the famous Paper Developer KennyTV.
UltimateClaims is made by songoda's Developer Team and Paper activly advises server admins to not buy nor use these plugins.

**Custom Recipes**
Well.. they will be added. I brought those up because they are just annoying to find and everyone want's them.

**MCMMO**
This is how to be the next uninteresting default SMP every server on earth has.
Not a great idea. It also has a history of breaking every block value in the economy there is once a certain skill level is reached by a player.

**Settings I made for the server as of now**

**SMP-1 Server Configuration for Customization and Optimization**
```
* Game World name set to: world_smp
* Fallback Message of the Day set to: ImperialValor SMP-1
* Difficulty set to: normal
* Maximal players set to: 100
* Disable vanilla fly check to prevent common false flags
* Set view dinstance to 10 (chunks) and simulation distance to 8 (chunks)
* Disabled vanilla spawn protection
* spawn-limits adjusted (in blocks):
    monsters: 25
    animals: 14
    water-animals: 5
    water-ambient: 20
    water-underground-creature: 5
    axolotls: 5
    ambient: 15
* Disabled restart on crash to prevent error loops
* Added color to default kick messages
* Removed command spam exclusions example
* merge-radius adjusted (in blocks):
    items: 2.5
    exp: 4.0
* Prevent zombie pigmens from spawning nether portals
* arrow-despawn-rate set to 600 (ticks)
* Disabled AI of mobspawner mobs to reduce spawner lag
* mob-spawn-range set to 6 (chunks)
* Reduced all entity activation ranges to recude entity movement lag
* Attempting to render chunks in front of players first instead of cicle like rendering
* Players can nolonger collide with each other to reduce player movement lag
* Using faster math formulars to calculate luck drops
* Limited book sizes to reduce the risk of book crashers
* Fixed headless pistons
* Fixed permanent block break exploits
* Fixed piston duplication
* Disabled username validation for bedrock players
* Using faster math to calculate suffocations
* Configured paper's anti xray mode 2
* Obfuscated item meta to confuse cheats
* Preventing players from moving into unloaded chunks
* Made all door breaking mobs do so in normal difficulty
* Made specific (junk) items despawn faster to reduce entity lag
* Spawning entities (mobs, animals etc) per player so everyone gets some
* Disabled thunder to reduce weather lag
* Using faster math formulars to optimize explosions
* Refilling lootables between 12h-2d
* Disabled end credits
* Changed redstone to faster eigencraft implementation
* Async mob spawning to prevent mob spawning lag
* entity_timeouts adjusted (in ticks):
    SNOWBALL: 600
    ARROW: 600
	ENDER_PEARL: 600
    LLAMA_SPIT: 600
* Limited broadcast to affected players only
* Patched F3+N Gamemode hotswap
* /gamemode now needs specific permissions like minecraft.command.gamemode.creative
* Fixed hidden entities appearing in entity selector, which exposes them
* Enderchest rows can now be added per permission (purpur.enderchest.rows.<number>)
* Crying obsidian is now valid for nether portal frame
* Grindstone can now remove curses
* Enabled tps-cacheup to try and restore server tick balance after lag
* /give command no longer drops when inventory overflows
* Disabled enderman griefing
* Disabled creeper griefing
* Iron Golem anger can be calmed with healing or poppy flower
* Disabled Enderdragon Egg teleportation
* Allow farmland moisture from below
* Disabled farmland trampling
* Fixed sand duping
* Disallow oversized item stacks in shulkers to slow down possible item dupes
* Using permissions to enable sign styling and editing
* Fixed water animal mobspawners being height dependent (mc-238526)
* Fixed turtle eggs breaking from EXP and item drops
* Disabled all armorstand movements treating it more like a block
* Mending will repair the most broken item with mending in the inventory first
* Entities will no longer use portals to prevent broken mobfarm and EXP mechanics
* Mobs will ignore rails to prevent the AI from breaking down
* Totem of Undying works from everywhere in the inventory
* Fixed players being stuck in portal bug
* Curse of Binding armor can be removed when entity has weakness
+ added bedrock support
```
**Important Notes**
*These values need adjustments after release.*
```
* Online Mode kept true, must be set to false later -> The server is used as standalone until the network has a correct setup.
* network-compression-threshold kept 256, must be set to -1 later (see reasoning above) 
* bungeecord-mode kept false, must be set to true later (see reasoning above)
* Bound network address must be set to protected when added to the network later
```

**Comment by West107** [comment]
Still go ahead with these features: 
Ranks
Do a 20k by 20k map since when we get new updates we can expand 
Auction house and trades seem good for economy instead of player shops
Ranks are fine rn we can add more perks later (added some money to rankup)
Choose the best claiming plugin where people can claim land, trust players, buy claimblocks

Add these features:
Zombie converts villagers to Zombie Villagers 100% of the time
Dynmap type system


Get rid of these:
Bedrock support 
Earth Map, just one world with 1.19
Disabled username validation for bedrock players
Entities will no longer use portals to prevent broken mobfarm and EXP mechanics

**Comment by Whitescan** [comment]
I'd do [BlueMap](https://www.spigotmc.org/resources/bluemap.83557/) for the webmap.

Any specific reason to get rid of Bedrock? Why are we restricting us to only Java players?

You do realise that after 10 of the portal farms our server will be dead to no avail?

**Comment by West107** [comment]
Bluemap seems alright to use

Introducing bedrock causes loads of problems especially on a network 

I really like portal farms but it is probably best to get rid of them

**Comment by Whitescan** [comment]
If there would be any problems with bedrock client's I assure you I would not do so.
I have 0 concerns that they will cause any trouble since I work for MUCH larger server networks doing the same.
I have like 2 years of experience running bedrock support on java servers.
Maybe when you take public stuff it is hard, but I designed all my stuff to work with it just fine.

**Comment by West107** [comment]
Also for the Economy:

1. We will have shops at spawn to set the minimal prices. 
2. We can put taxes on player shops 

We need a plugin for npc server shops and shops for players to setup

**Comment by Whitescan** [comment]
Feature has been implemented.
