### ISSUE TITLE
Consolidating multiple plugins into a Spigot and a BungeeCord one

### ISSUE THREAD

**Issue by chriscn** [imperialvalordev/helpdesk#8]
Currently Imperial Valor network has around ~10 plugins which are custom written and work well, however there is a lot of duplication and it would be beneficial to consolidate all of these into one plugin for each platform.

### Pros
- Reduces duplicate code, we are using the command framework on all plugins which is fine but isn't required
- Allows us to just update one plugin (see section on CI/CD below)
- One database handler rather than copying the same boilerplate
### Cons
- Would be a large codebase that may become difficult to manage

## Architecture
The plugin would be comprised of different 'modules' that would load and unload different sections depending on the need of the indidivual server (hub would want doublejump, survival wouldn't) now this could be done programatically or by a permission node. Personally the first approach is better.

### CI/CD
It would be amazing (and something within scope) that when a release is created it would build and then deploy the plugin to all servers defined in a scope. Each server would have a custom `configuration.yaml` file with what it needs.

We could also setup a CRON job so that every week it would automatically build the plugin with the latest version of Paper and deploy it so that it is always up to date.

### Plugins
`IVNetwork` (name tbc) would consist of:
- IVPlaytime
- BroadcastTitle
- StaffTools
- Vanish
- Heros
- Cerberus

`IVServer` (again name tbc) would consist of:
- coresurvial
- antiportal?
- DoubleJump

Big projects like `RunFromTheBeast` and `Artemis` would still have their own plugins but as a base I think this could be a good idea.

**Comment by chriscn** [comment]
Following on from this (and I've thought about it a little more).
## Architecture of a Module
Each `module` would be responsible for:
- Registering its commands
- Registering its events
- Registering all of its logic

An interface may be the best way of achieving this and creating a module framework would be great with descriptions. I'm a little excited lol

**Comment by chriscn** [comment]
[TitanAPI](https://github.com/imperialvalordev/TitanAPI) would be paused whilst this project is completed. However once TitanAPI is stable I'd like to incorporate it in a v2 of this?

**Comment by Whitescan** [comment]
> Reduces duplicate code, we are using the command framework on all plugins which is fine but isn't required
There are times where the command framework just feels too much. For example BungeeCord does a good job when using the all args constructor. I see no need to use it on there. It still needs to be shaded into the jar which takes up (little) space. Is this really nessesary? I feel like you and me are the only people using it. And I only do so if needed. Makes the work environment more complex which is not what it's supposed to do. I'd say it only shines when having 5+ commands in one plugin or "module" (when referring to the new architecutre).

> One database handler rather than copying the same boilerplate
Well when looking at [TitanAPI](https://github.com/imperialvalordev/TitanAPI) it can be deployed on both bungee and spigot based servers. The _compile_ scope should only be used when making a standalone or test version of the plugin. For testing purposes TitanAPI even provides a SQLite Database which fakes an actual database. 
So you could say I already addressed that problem and solved it?

> Would be a large codebase that may become difficult to manage
Even so this is a single point it's HUGE. The maintainablity let alone working on it with a big team will result in huge chaos when non qulified people work on it. Since everything is so nested, the changes will eventually infect other parts. 
When the plugin breaks down because of the DoubleJump for example, it might disable and make the lobby essentially vanilla. This makes the server and network really vulnerable. Inspiered by Java's Object orientated programming, we should split stuff in logically separated parts as we may or may not have done before. That's exactly why Java is how it is. Because (ex-sun) Oracle realised the "one massive big thing approach" is not a great idea. So sorry. This is where I disagree completely. 
But I'll continue on my feedback for now.

> The plugin would be comprised of different 'modules' that would load and unload different sections depending on the need of > the indidivual server (hub would want doublejump, survival wouldn't) now this could be done programatically or by a 
> permission node. Personally the first approach is better.
Yes. If such a thing will be implemented it should not rely on something the end user of our product can mess up that easy. 

> CI/CD
Well all of that is perfectly valid. But can also be achived no matter how we will handle stuff in the future.

> Plugins
Logacally you devide minecraft plugins in one major and one sub category. 

Major-Categories would be **Bungee**, **Spigot** or **Universial/Shared**

Sub-Categories would are a bit more tricky. But could be devided into **Staff**, **Utitlity**, **Mechanic**, **Standalone (RFTB or LobbySystem for example)** or **Security**. 

**Conclusion**
I do not support this. TitanAPI will handle stuff like Util classes, database management, config management and shared stuff f.e. playerstats or something else (that was the first I could think of).

**Comment by chriscn** [comment]
Thanks @Whitescan these are all really good points, I was saddened to hear your strong conclusion for the project and hope that I'll address your concerns and provide you with some thoughts. I decided to start it today as a proof of concept which you can see: [IVNetwork](https://github.com/imperialvalordev/IVNetwork) - although I am sure you've already seen it.

> Command Framework
I do agree with this - I personally do really like the framework but as you've said it does make the codebase much more complex espically for smaller projects. I've added it to the Network plugin as I feel that is where it is most utilisised as I imagine lots of commands across many different modules

> TitanAPI
I misunderstood what TitanAPI does and for that I apologise, I believe that TitanAPI would be really useful in this project specifically for the database features that you've programmed. I'll look at implementing it as soon as I've got a POC, or you could ;-) 

> Largeness of the project
Using your category system each Major would be a seperate plugin on a different repo - it is the easiest way of handling it in my opinion. In order to create a massive inoperable codebase, each module will register its own listeners/commands/everything internally. This would effectively make them idemptonent and allow better understanding since if DoubleJump failed it would only be in the DoubleJump module.

For complete codebase take a look but in brief each module implements an interface `IVModule` which contains the methods it must have.

My idea is to allow enabling and disabling within the config file (along with extra configuration for each module). 

Each module has a category (provided by an enum) - that would allow filtering etc

> Since everything is so nested, the changes will eventually infect other parts
A module **MUST NOT** interact with another module in anyway. It should be self contained.

> CI/CD
Yes it could be easily done on the per project level but I'd rather not have to manually set it up for each project.

**Comment by Whitescan** [comment]
> Command Framework

Agreed. Makes sense in large projects. Little in small ones. And medium in medium siced ones. Pretty straight forward when asking "should I use it?"

> TitanAPI

You can see this project as the very very base of all our projects. It just does regular jobs. Stuff you'll need anyways.
There will be a config? Handled. There will be a database of some sort? Sure get the implementation you want. (SQLite and MySQL currently). You need to sort players by something you've already written? Go ahead use the TitanAPI Util. You get the point. You just **__NEED IT EVERYWHERE__**

> Largeness of the project

Looking forward to your POC. From what I've seen right now I'm still not convinced. But since you addressed my concerns I'm willing to sit back and enjoy the show. If it does great, well, fine? If not then it just proofed that we stay where we are. (Might want to address the problem with duplicate code anyways).

> Since everything is so nested, the changes will eventually infect other parts

Well in the end all plugins run in one JVM. If f.e. a runtime error occures for DoubleJump because it exceeds the Thread limit or god knows what, the entire server will shut down. Your modlues are only in our heads. Not really visible for the compiler at bytecode level.

> CI/CD

Well. Agreed. Multiple tasks increase the chance of something going south. But that's a different matter if you ask me.

**Comment by chriscn** [comment]
I've implemented StaffChat in a way that I am happy with, it works well - isn't bulletproof but there we go.

The one thing I'm not sure @Whitescan and hoping you'll lend your assistance is getting the module classname from a string and enabling it. I'll explain below

1. Plugin loops through config file which contains all modules
2. If enabled = true, get the class which will be in the package `net.imperialvalor.ivnetwork.<slug>.<Module Name>` 
3. Call its enabled method

**Slug:** a lowercase reference e.g. staffchat,staffreport etc
**ModuleName:** same as class name e.g. StaffChat, StaffReport

**Comment by aarushbhutra** [comment]
Just wanted to add something maybe make a IVStaff for Vanish and StaffUtils, would be useful

**Comment by Whitescan** [comment]
This is not being continued.
